# Generated by Django 5.2 on 2025-05-03 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandose_misty_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomprice",
            name="room_type",
            field=models.CharField(
                choices=[("Deluxe", "Deluxe Room"), ("Suite", "Suite Room")],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roomprice",
            name="price_per_night",
            field=models.DecimalField(
                decimal_places=2, help_text="Original price per night", max_digits=10
            ),
        ),
    ]
